#!/usr/bin/env groovy

def random_string_generator() {
    StringBuilder sb = new StringBuilder("xyz");
    def random = new Random();
	for(int i=0;i<6;i++) {
	    sb.append(random.nextInt(10));
	}
    return sb.toString();
}

def generateDotENV() {
    String env_vars = "";
    env_vars = env_vars.concat("WORDPRESS_ADMIN_USER=" + random_string_generator()+"\n");
    env_vars = env_vars.concat("WORDPRESS_ADMIN_PASS=" + random_string_generator()+"\n");
    env_vars = env_vars.concat("MYSQL_DB_USER=" + random_string_generator()+"\n");
    writeFile(file: '.env', text: env_vars);
}

pipeline {
   agent any
   stages {
       stage("Init") {
           steps {
               echo "Running init stage inside project1."
               generateDotENV()
               echo "cat .env"
           }
       }
       stage("build") {
           steps {
               echo "Running build stage inside project1."
           }
       }
       stage("test") {
           steps {
               echo "Running test stage inside project1."
           }
       }
       stage("deploy") {
           steps {
               echo "Running deploy stage inside project1."
           }
       }
   }
   // post {
       // always {
       //     mail to: 'jkumar@cognam.com',
       //    subject: "Result Pipeline: ${currentBuild.fullDisplayName}",
       //    body: "Please check here: ${env.BUILD_URL}"
       // }
   // }
}
