#!/usr/bin/env groovy

def random_string_generator() {
    String charset = (('a'..'z')+('0'..'9')).join();
    println(charset)
    int n = 8;
    return new Random().with {
       (1..n).collect { charset[ nextInt( charset.length() ) ] }.join()
   }
}

pipeline {
   agent any
   stages {
       stage("Init") {
           steps {
               echo "Running init stage inside project1."
               def st = random_string_generator();
               echo st;
           }
       }
       stage("build") {
           steps {
               echo "Running build stage inside project1."
           }
       }
       stage("test") {
           steps {
               echo "Running test stage inside project1."
           }
       }
       stage("deploy") {
           steps {
               echo "Running deploy stage inside project1."
           }
       }
   }
   // post {
       // always {
       //     mail to: 'jkumar@cognam.com',
       //    subject: "Result Pipeline: ${currentBuild.fullDisplayName}",
       //    body: "Please check here: ${env.BUILD_URL}"
       // }
   // }
}
